print("Enter the radius value: ");
$r=<>;
print("Enter the edge value: ");
$a=<>;
print("Enter the height value: ");
$h=<>;
print("Enter the breadth value: ");
$b=<>;
$arofcircle=3.14*$r*$r;
$arofsquare=$a*$a;
$arofrectangle=$h*$b;
print("Area of the circle is: ");
print($arofcircle);
print("\n");
print("Area of the square is: ");
print($arofsquare);
print("\n");
print("Area of the rectangle is: ");
print($arofrectangle);
print("\n");